language: node_js
node_js:
  - "6"
  - "4"
addons:
  - firefox: "47.0"
matrix:
  fast_finish: true
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - eslint src
  - npm run build
  - node_modules/.bin/karma start test/karma.travis.conf.js --single-run
