language: node_js
node_js:
  - "6"
  - "5"
  - "4"
addons:
  firefox: "46.0"
matrix:
  fast_finish: true
script:
  - eslint src
  - npm run build
  - node_modules/.bin/karma start test/karma.travis.conf.js --single-run
